defaults: &defaults
  host: dharma.mongohq.com
  port: 10060
  username: ag-admin
  password: ag-pw-vortexSutra1
  database: app17225840
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  # <<: *defaults
  # database: locomotive_dev
  sessions:
    default:
      # host: dharma.mongohq.com
      # port: 10060
      # username: ag-admin
      # password: ag-pw-vortexSutra1
      # database: app17225840
      uri: "mongodb://ag-admin:ag-pw-vortexSutra1@dharma.mongohq.com:10060/app17225840"
  
test:
  <<: *defaults
  database: locomotive_test

# set these environment variables on your prod server
production:
  # <<: *defaults
  # database: locomotive_prod

  # other settings for production
  # host: <%= ENV['MONGOID_HOST'] %>
  # port: <%= ENV['MONGOID_PORT'] %>
  # username: <%= ENV['MONGOID_USERNAME'] %>
  # password: <%= ENV['MONGOID_PASSWORD'] %>
  # database: <%= ENV['MONGOID_DATABASE'] %>

  # heroku
  # uri: <%= ENV['MONGOHQ_URL'] %>

  # bushido (mongohq_url will also work)
  default:
    uri: "mongodb://ag-admin:ag-pw-vortexSutra1@dharma.mongohq.com:10060/app17225840"